version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - "APP_PORT=${APP_PORT}"
      - "APP_BASEURL=${APP_BASEURL}"
    volumes:
        - ./db:/microservice/db